- name: Add ssh key for simone
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID7nQs060xGVqKx1TIcRFaYc5XGVXZkA4Pqfej6tGKJ1 ansible"

- name: generate sshd_config file from the template
  tags: ssh
  template: 
    src: "{{ ssh_template_file  }}"
    dest: /etc/ssh/sshd_config 
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd

